"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { createPortal } from "react-dom";
import axios from "axios";

const API_BASE = (process.env.NEXT_PUBLIC_DOCTOR_API_URL || process.env.NEXT_PUBLIC_API_URL) || "http://localhost:8080/api";
const PAGE_SIZE = 15;

function authHeaders() {
  const t = typeof window !== "undefined" ? localStorage.getItem("token") : "";
  return { Authorization: `Bearer ${t}` };
}
function fmtDate(d) {
  if (!d) return "—";
  return new Date(d).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}
function getInitials(name = "") {
  return name.trim().split(/\s+/).map((w) => w[0]).slice(0, 2).join("").toUpperCase() || "?";
}

// ─────────────────────────────────────────────────────────────────────────────
// PRESCRIPTION DETAIL MODAL
// ─────────────────────────────────────────────────────────────────────────────

function PrescriptionModal({ open, rx, onClose }) {
  const printRef = useRef(null);

  const handlePrint = () => {
    const w = window.open("", "_blank");
    if (!w) return;
    w.document.write(`
      <html><head><title>Prescription – ${rx?.diagnosis}</title>
      <style>
        body { font-family: 'Segoe UI', sans-serif; padding: 32px; color: #1a1a2e; }
        h1 { font-size: 20px; margin-bottom: 4px; }
        .meta { color: #666; font-size: 13px; margin-bottom: 24px; }
        .section { margin-bottom: 20px; }
        .section h3 { font-size: 11px; text-transform: uppercase; letter-spacing: .08em; color: #888; margin-bottom: 8px; }
        .med { background: #f0f7ff; border: 1px solid #cde; border-radius: 8px; padding: 10px 14px; margin-bottom: 8px; }
        .med p { margin: 2px 0; font-size: 13px; }
        .badge { font-size: 11px; background: #e8f0fe; color: #1a56db; padding: 2px 8px; border-radius: 20px; display: inline-block; }
        hr { border: none; border-top: 1px solid #eee; margin: 20px 0; }
        @media print { button { display: none !important; } }
      </style></head><body>
      <h1>Prescription</h1>
      <div class="meta">
        Patient: <strong>${rx?.patientId?.name || "—"}</strong> &nbsp;·&nbsp;
        Issued: <strong>${fmtDate(rx?.issuedAt)}</strong>
        ${rx?.followUpDate ? `&nbsp;·&nbsp; Follow-up: <strong>${fmtDate(rx.followUpDate)}</strong>` : ""}
      </div>
      <div class="section"><h3>Diagnosis</h3><p>${rx?.diagnosis || "—"}</p></div>
      <div class="section"><h3>Medications</h3>
        ${(rx?.medications || []).map((m) => `
          <div class="med">
            <p><strong>${m.name}</strong></p>
            <p>${[m.dosage, m.frequency, m.duration].filter(Boolean).join(" · ")}</p>
            ${m.instructions ? `<p style="color:#d97706;font-size:12px">${m.instructions}</p>` : ""}
          </div>`).join("")}
      </div>
      ${rx?.notes ? `<div class="section"><h3>Notes</h3><p>${rx.notes}</p></div>` : ""}
      <hr/>
      <p style="font-size:11px;color:#aaa">Generated by MediCare Doctor Portal</p>
      <script>window.onload = () => { window.print(); window.close(); }</script>
      </body></html>
    `);
    w.document.close();
  };

  if (!open || !rx || typeof window === "undefined") return null;

  return createPortal(
    <div className="fixed inset-0 z-[200] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/50 backdrop-blur-sm" onClick={onClose} />
      <div ref={printRef}
        className="relative w-full max-w-lg bg-white rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh] animate-[scaleIn_.2s_ease-out]">

        {/* Header */}
        <div className="flex items-center gap-3 px-6 py-4 border-b border-gray-100 bg-gradient-to-r from-blue-50 to-cyan-50 shrink-0">
          <div className="w-10 h-10 rounded-xl bg-blue-600 flex items-center justify-center text-white shrink-0">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
          </div>
          <div className="min-w-0">
            <p className="text-sm font-bold text-gray-900 truncate">{rx.diagnosis}</p>
            <p className="text-xs text-gray-500">
              {rx.patientId?.name || "Patient"} · {fmtDate(rx.issuedAt)}
            </p>
          </div>
          <div className="ml-auto flex items-center gap-2">
            <button onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-blue-200 text-blue-600 text-xs font-bold hover:bg-blue-50 transition-colors">
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" /></svg>
              Print
            </button>
            <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-gray-200 text-gray-400 hover:text-gray-600">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
            </button>
          </div>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-5">
          {/* Meta */}
          <div className="flex flex-wrap gap-2">
            <span className="px-3 py-1 bg-blue-50 text-blue-700 text-xs font-semibold rounded-full border border-blue-200">
              Issued: {fmtDate(rx.issuedAt)}
            </span>
            {rx.followUpDate && (
              <span className="px-3 py-1 bg-amber-50 text-amber-700 text-xs font-semibold rounded-full border border-amber-200">
                Follow-up: {fmtDate(rx.followUpDate)}
              </span>
            )}
          </div>

          {/* Diagnosis */}
          <div>
            <p className="text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-2">Diagnosis</p>
            <div className="px-4 py-3 bg-gray-50 rounded-xl border border-gray-200 text-sm text-gray-800">{rx.diagnosis}</div>
          </div>

          {/* Medications */}
          <div>
            <p className="text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-2">
              Medications ({(rx.medications || []).length})
            </p>
            <div className="space-y-2">
              {(rx.medications || []).length === 0
                ? <p className="text-sm text-gray-400 italic">No medications prescribed</p>
                : rx.medications.map((m, i) => (
                  <div key={i} className="bg-blue-50 border border-blue-100 rounded-xl p-4">
                    <div className="flex items-start justify-between gap-2">
                      <p className="text-sm font-bold text-gray-900">{m.name}</p>
                      <span className="text-[10px] font-bold text-blue-600 bg-blue-100 px-2 py-0.5 rounded-md shrink-0">
                        #{i + 1}
                      </span>
                    </div>
                    <div className="flex flex-wrap gap-x-3 gap-y-0.5 mt-1.5">
                      {[[m.dosage, "Dosage"], [m.frequency, "Frequency"], [m.duration, "Duration"]].map(([val, lbl]) =>
                        val ? <p key={lbl} className="text-xs text-gray-500"><span className="font-medium text-gray-700">{val}</span> <span className="text-gray-400">({lbl})</span></p> : null
                      )}
                    </div>
                    {m.instructions && (
                      <p className="text-xs text-amber-700 mt-1.5 bg-amber-50 px-2.5 py-1 rounded-lg border border-amber-100">
                        📋 {m.instructions}
                      </p>
                    )}
                  </div>
                ))
              }
            </div>
          </div>

          {/* Notes */}
          {rx.notes && (
            <div>
              <p className="text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-2">Additional Notes</p>
              <div className="px-4 py-3 bg-amber-50 border border-amber-100 rounded-xl text-sm text-gray-700">{rx.notes}</div>
            </div>
          )}
        </div>
      </div>
    </div>,
    document.body
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// PAGINATION
// ─────────────────────────────────────────────────────────────────────────────

function Pagination({ page, total, pageSize, onChange }) {
  const totalPages = Math.ceil(total / pageSize);
  if (totalPages <= 1) return null;
  return (
    <div className="flex items-center justify-center gap-1.5 pt-4">
      <button onClick={() => onChange(page - 1)} disabled={page === 1}
        className="w-8 h-8 flex items-center justify-center rounded-lg border border-gray-200 text-gray-500 hover:bg-gray-50 disabled:opacity-40 text-xs">‹</button>
      {Array.from({ length: totalPages }, (_, i) => i + 1).map((p) => (
        <button key={p} onClick={() => onChange(p)}
          className={`w-8 h-8 rounded-lg text-xs font-semibold transition-colors
            ${p === page ? "bg-blue-600 text-white shadow-sm" : "border border-gray-200 text-gray-600 hover:bg-gray-50"}`}>
          {p}
        </button>
      ))}
      <button onClick={() => onChange(page + 1)} disabled={page === Math.ceil(total / pageSize)}
        className="w-8 h-8 flex items-center justify-center rounded-lg border border-gray-200 text-gray-500 hover:bg-gray-50 disabled:opacity-40 text-xs">›</button>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// MAIN PAGE
// ─────────────────────────────────────────────────────────────────────────────

export default function PrescriptionsPage() {
  const [prescriptions, setPrescriptions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState(null); // prescription to view in modal

  const fetchPrescriptions = useCallback(async () => {
    setLoading(true);
    try {
      const { data } = await axios.get(`${API_BASE}/doctors/prescriptions`, { headers: authHeaders() });
      setPrescriptions(data.prescriptions || data || []);
    } catch (err) {
      console.error("Prescriptions fetch error:", err.message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchPrescriptions(); }, [fetchPrescriptions]);

  // Client-side filter
  const filtered = prescriptions.filter((rx) => {
    const name = (rx.patientId?.name || rx.patientName || "").toLowerCase();
    const meds = (rx.medications || []).map((m) => m.name?.toLowerCase()).join(" ");
    const q = search.toLowerCase();
    const matchSearch = !search || name.includes(q) || meds.includes(q) || rx.diagnosis?.toLowerCase().includes(q);
    const issued = rx.issuedAt ? new Date(rx.issuedAt) : null;
    const matchFrom = !fromDate || (issued && issued >= new Date(fromDate));
    const matchTo = !toDate || (issued && issued <= new Date(toDate + "T23:59:59"));
    return matchSearch && matchFrom && matchTo;
  });

  const paginated = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  const clearFilters = () => { setSearch(""); setFromDate(""); setToDate(""); setPage(1); };

  return (
    <>
      <PrescriptionModal open={!!selected} rx={selected} onClose={() => setSelected(null)} />

      <div className="max-w-6xl mx-auto space-y-5">
        {/* Header */}
        <div className="flex items-start justify-between gap-4 flex-wrap">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Prescriptions</h1>
            <p className="text-sm text-gray-500 mt-0.5">
              {loading ? "Loading…" : `${filtered.length} prescription${filtered.length !== 1 ? "s" : ""}`}
            </p>
          </div>
        </div>

        {/* Filters */}
        <div className="flex flex-wrap gap-3">
          <div className="relative flex-1 min-w-48">
            <svg className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
            <input type="text" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }}
              placeholder="Search by patient, medication, or diagnosis…"
              className="w-full pl-9 pr-4 py-2.5 rounded-xl border border-gray-200 text-sm text-gray-800 placeholder-gray-400
                focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white transition" />
          </div>
          <div className="relative">
            <span className="absolute left-3 top-1/2 -translate-y-1/2 text-[10px] font-bold text-gray-400">FROM</span>
            <input type="date" value={fromDate} onChange={(e) => { setFromDate(e.target.value); setPage(1); }}
              className="pl-14 pr-3 py-2.5 rounded-xl border border-gray-200 text-sm text-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white transition" />
          </div>
          <div className="relative">
            <span className="absolute left-3 top-1/2 -translate-y-1/2 text-[10px] font-bold text-gray-400">TO</span>
            <input type="date" value={toDate} onChange={(e) => { setToDate(e.target.value); setPage(1); }}
              className="pl-10 pr-3 py-2.5 rounded-xl border border-gray-200 text-sm text-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white transition" />
          </div>
          {(search || fromDate || toDate) && (
            <button onClick={clearFilters} className="px-3 py-2.5 rounded-xl border border-gray-200 text-xs font-semibold text-gray-500 hover:bg-gray-50 transition-colors">Clear ✕</button>
          )}
        </div>

        {/* Table */}
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
          {/* Table header */}
          <div className="grid grid-cols-12 gap-2 px-5 py-3 bg-gray-50 border-b border-gray-100 text-[10px] font-bold text-gray-400 uppercase tracking-wider">
            <div className="col-span-2">Date</div>
            <div className="col-span-3">Patient</div>
            <div className="col-span-3">Diagnosis</div>
            <div className="col-span-3 hidden md:block">First Medication</div>
            <div className="col-span-1 text-right">Actions</div>
          </div>

          {/* Rows */}
          {loading ? (
            <div className="divide-y divide-gray-100">
              {Array.from({ length: 8 }).map((_, i) => (
                <div key={i} className="grid grid-cols-12 gap-2 px-5 py-3.5 animate-pulse">
                  <div className="col-span-2 h-3 bg-gray-100 rounded" />
                  <div className="col-span-3 h-3 bg-gray-100 rounded" />
                  <div className="col-span-3 h-3 bg-gray-100 rounded" />
                  <div className="col-span-3 h-3 bg-gray-100 rounded hidden md:block" />
                  <div className="col-span-1 h-6 bg-gray-100 rounded-lg" />
                </div>
              ))}
            </div>
          ) : paginated.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-16">
              <div className="w-14 h-14 rounded-2xl bg-gray-100 flex items-center justify-center text-2xl mb-3">📋</div>
              <p className="text-sm font-semibold text-gray-700">No prescriptions found</p>
              <p className="text-xs text-gray-400 mt-1">Try adjusting your search or filters</p>
            </div>
          ) : (
            <div className="divide-y divide-gray-100">
              {paginated.map((rx) => {
                const patientName = rx.patientId?.name || rx.patientName || "Unknown Patient";
                const firstMed = rx.medications?.[0];
                return (
                  <div key={rx._id}
                    className="grid grid-cols-12 gap-2 items-center px-5 py-3.5 hover:bg-blue-50/30 transition-colors group">
                    {/* Date */}
                    <div className="col-span-2">
                      <p className="text-xs font-semibold text-gray-700">{fmtDate(rx.issuedAt)}</p>
                    </div>
                    {/* Patient */}
                    <div className="col-span-3 flex items-center gap-2 min-w-0">
                      <div className="w-7 h-7 rounded-full bg-gradient-to-br from-blue-500 to-cyan-400 flex items-center justify-center text-white text-[10px] font-bold shrink-0">
                        {getInitials(patientName)}
                      </div>
                      <p className="text-xs font-semibold text-gray-800 truncate">{patientName}</p>
                    </div>
                    {/* Diagnosis */}
                    <div className="col-span-3">
                      <p className="text-xs text-gray-700 truncate" title={rx.diagnosis}>{rx.diagnosis}</p>
                      {rx.followUpDate && (
                        <p className="text-[10px] text-amber-600 mt-0.5">↩ {fmtDate(rx.followUpDate)}</p>
                      )}
                    </div>
                    {/* First medication */}
                    <div className="col-span-3 hidden md:block">
                      {firstMed ? (
                        <div>
                          <p className="text-xs font-medium text-gray-800 truncate">{firstMed.name}</p>
                          <p className="text-[10px] text-gray-400">{[firstMed.dosage, firstMed.frequency].filter(Boolean).join(" · ")}</p>
                        </div>
                      ) : (
                        <p className="text-xs text-gray-300 italic">None</p>
                      )}
                    </div>
                    {/* Actions */}
                    <div className="col-span-1 flex justify-end">
                      <button onClick={() => setSelected(rx)}
                        className="px-3 py-1.5 rounded-xl border border-gray-200 text-gray-600 text-xs font-bold
                          hover:bg-blue-50 hover:border-blue-300 hover:text-blue-600 transition-all group-hover:border-blue-200">
                        View
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        <Pagination page={page} total={filtered.length} pageSize={PAGE_SIZE}
          onChange={(p) => { setPage(p); window.scrollTo({ top: 0, behavior: "smooth" }); }} />
      </div>

      <style>{`@keyframes scaleIn { from { opacity:0; transform:scale(0.96); } to { opacity:1; transform:scale(1); } }`}</style>
    </>
  );
}
